web:
    build: .
    dockerfile: Dockerfile
    ports:
        - "80:80"
    volumes:
        - ~/nginx-php/phphub5:/lbbniu/wwwroot
        - ~/nginx-php/nginx.conf:/lbbniu/nginx/conf/nginx.conf
    working_dir: /lbbniu/wwwroot
    links:
        - mysql
        - redis
        - memcached
mysql:
    image: mysql
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        - MYSQL_ROOT_PASSWORD=lbbniu

redis:
    image: redis
    ports:
        - "6379:6379"
    expose:
        - "6379"
memcached:
    image: memcached   
    ports:
        - "11211:11211"
    expose:
        - "11211" 