hvacronline:
    image: nginx:1.11.4
    ports:
        - "80:80"
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./logs:/data/logs
        - ./wwwroot:/data/wwwroot
    working_dir: /data/wwwroot
    links:
        - phpfpm
        - mysql
phpfpm:
    image: hvacronline_phpfpm
    #build: .
    #dockerfile: Dockerfile-php
    volumes:
        - ./conf/php.ini:/usr/local/etc/php/php.ini
        - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./logs:/data/logs
        - ./wwwroot:/data/wwwroot
    working_dir: /data/wwwroot
    links:
        - mysql
    expose:
        - "9000" 
    dns:
        - 114.114.114.144
        - 8.8.8.8        
mysql:
    image: mysql:5.6
    expose:
        - "3306"
    volumes:
        - ./conf/my.cnf:/etc/mysql/my.cnf
        - ./data:/data
    working_dir: /data
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - DATADIR=/data
        - MYSQL_DATABASE=hvacronline